// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#ifndef __WINDOWSAPPSDK_VERSIONINFO_H__
#define __WINDOWSAPPSDK_VERSIONINFO_H__

#define WINDOWSAPPSDK_RELEASE_MAJOR                1
#define WINDOWSAPPSDK_RELEASE_MINOR                0
#define WINDOWSAPPSDK_RELEASE_PATCH                0
#define WINDOWSAPPSDK_RELEASE_MAJORMINOR           0x00010000

#define WINDOWSAPPSDK_RELEASE_CHANNEL              "preview"
#define WINDOWSAPPSDK_RELEASE_CHANNEL_W            L"preview"

#define WINDOWSAPPSDK_RELEASE_VERSION_TAG          "preview2"
#define WINDOWSAPPSDK_RELEASE_VERSION_TAG_W        L"preview2"

#define WINDOWSAPPSDK_RELEASE_VERSION_SHORTTAG     "p2"
#define WINDOWSAPPSDK_RELEASE_VERSION_SHORTTAG_W   L"p2"

#define WINDOWSAPPSDK_RELEASE_VERSION_MAJOR             0
#define WINDOWSAPPSDK_RELEASE_VERSION_MINOR             272
#define WINDOWSAPPSDK_RELEASE_VERSION_BUILD             1934
#define WINDOWSAPPSDK_RELEASE_VERSION_REVISION          0
#define WINDOWSAPPSDK_RELEASE_VERSION_UINT64            0x00000110078E0000
#define WINDOWSAPPSDK_RELEASE_VERSION_DOTQUADSTRING     "0.272.1934.0"
#define WINDOWSAPPSDK_RELEASE_VERSION_DOTQUADSTRING_W   L"0.272.1934.0"

#endif // __WINDOWSAPPSDK_VERSIONINFO_H__
